### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by OnkelTem** [orta/playground-slides#16]
Hi!
I discovered this plugin in the TS Playground and activated it.
Then I went to create a gist here: https://gist.github.com/OnkelTem/46abb04c4705e3a276f8313222903c81 and pasted its link in the corresponding box.
Now I see a few slides at the top of the page, above my sandbox. But what's next, really? They don't seem to be connected in any way so what I am assumed to see/experience?
Do you have an example?

Btw, the link to "an existing deck" doesn't lead anywhere:

![image](https://user-images.githubusercontent.com/114060/171489924-d67307a3-f8da-4294-ad00-fa34e2be1959.png)

**Comment by orta** [comment]
You can see it in action here: https://www.youtube.com/watch?v=wOOT50zqw9w

**Comment by OnkelTem** [comment]
Thank you for sharing that. I've watched the video but I'm still not sure how the slides are connected to the code in a sandbox.

**Comment by orta** [comment]
Ah yeha, that's the wrong video. 

Did you read the README, it has examples from a deck I used?

Yeah, this plugin is slides that live above the playground, and the slides can set the playground's code, all based on a gist - I'm not too sure what else you want from it?

**Comment by OnkelTem** [comment]
> Did you read the README, it has examples from a deck I used?

Of course I did.

> Yeah, this plugin is slides that live above the playground, and the slides can set the playground's code, all based on a gist

Ah, that! Now, I see. I was missing exactly this point :)

Ok, let me show you why I think it went that way. It basically was a chain of unforeseen coincidences :)

The first thing I did was to open the README.md. But the first example was like:

![image](https://user-images.githubusercontent.com/114060/171684565-5e4c2a48-5a1c-4413-9c18-9cbf701cf894.png)

So it was not obvious that the slides are really connected with the playground code.

Then, below, there is a mention of the key mechanism — the `<playground>` element. But it isn't rendered as a `code`:

![image](https://user-images.githubusercontent.com/114060/171683948-c1dac078-27e6-4f2d-a1b9-70ff250983ce.png)

So I missed it one more time (And I didn't notice that element in the subsequent snippet, although it was right there...).

The third thing was the example itself: https://github.com/orta/playground-slides/blob/master/examples/tsnyc-jan-2020.md
If you view it in the reading mode the `<Playground>` element is not visible :)

![image](https://user-images.githubusercontent.com/114060/171687307-6adcdcee-1a25-4e3e-92b4-838840b4d3c7.png)


Phew!

I'm still not sure how I can use it, but at least now it's clear how to use it. Many years ago I was preparing slideshows in Inkscape, using one of its plugins. I'm just a a fan of visualizations. And I discovered Reveal.js just yesterday and plan to study it. Thanks!

**Comment by orta** [comment]
Nice spot!

**Comment by orta** [comment]
I've also made it more obvious https://github.com/orta/playground-slides/commit/0dd413e5a3e8788b74bf85a0d37dce8ab5b7c388

**Comment by OnkelTem** [comment]
Even better, yay! :)
